### ISSUE TITLE
Final test answers

### ISSUE THREAD

**Issue by pratyush6717** [Internshala-Online-Trainings/React#2]
There is one missing module that is final test , if anyone have then do update it!

**Comment by singhamrish360** [comment]
Hey , i am also looking for final test solution , please send me to singhamrish360@gmail.com

**Comment by ashish-khankari** [comment]
can I work on your issue

**Comment by anshviyogi** [comment]
@ashish-khankari, just find the solution and create a pull request of it

**Comment by pratyush6717** [comment]
obsolete
